### ISSUE TITLE
Reducer should use action.type and be called with action.payload as its arg

### ISSUE THREAD

**Issue by rynocouse** [MadeInHaus/react-redux-webpack-starter#12]
https://github.com/MadeInHaus/react-redux-webpack-starter/blob/a6088771b2d0d1c694372e7e1c95b391269b7143/src/reducers/app.js#L11

**Comment by cjthedizzy** [comment]
This is fixed in the fix-reducer-example branch. Would also like to add an example of a state setter/action before merging. Suggestions on what that should be?

@stevescavo @rynocouse

**Comment by rynocouse** [comment]
I'd like to see samples of a few typical things like: async fetch, some ui state and maybe a input of sorts? this all might be too much sample code

**Comment by cjthedizzy** [comment]
I think async for sure and something simple like UI state. We should do it in one component so its easy to tear out. Also a selector
