### ISSUE TITLE
CSS Utility classes

### ISSUE THREAD

**Issue by unruffledBeaver** [MadeInHaus/react-redux-webpack-starter#22]
Right now our utilities are not very good or useful for what we commonly build. This issue is to discuss updating our files/strategy for making better use of utility classes

A candidate for this would:
- Help reduce redundant class declarations
- Make component styles easier to follow by reducing noise
- Works in media queries and pseudo selectors

**Comment by unruffledBeaver** [comment]
Possible third party solutions:

https://tailwindcss.com/
http://tachyons.io/

**Comment by stevescavo** [comment]
I think taking a css utility class approach isn't probably too opinionated for this starter and for what we, as a dev team, typically do. Our team and others can make use of our typography UI components and roll their own layout components as needed based upon a project's unique set of requirements.
