### ISSUE TITLE
Remove `react-css-modules`

### ISSUE THREAD

**Issue by unruffledBeaver** [MadeInHaus/react-redux-webpack-starter#27]
This package is the one that gives us the `styleName` attribute. I feel that it makes reasoning about things a bit harder especially when youre passing classNames through to another element. Also it is a pain to import multiple stylesheets. I think it does more harm than good.

Its only benefits are:
- Not having to reference every class from an object
- hyphenated classNames with having to use bracket notation

**Comment by stevescavo** [comment]
I'm all for removing this package dependency.
