### ISSUE TITLE
Add `env-cmd` and setup `publicPath`

### ISSUE THREAD

**Issue by unruffledBeaver** [MadeInHaus/react-redux-webpack-starter#5]
`env-cmd` lets us run our webpack build using our `.env` file so that webpack can grab those values to configure its output. We can use this to setup the production builds `publicPath` to point to cloudfront, aws, your moms house, etc. `publicPath` is prepended to all assets that are imported or sourced by webpack

**Comment by cjthedizzy** [comment]
**ALSO:** Fix Globals

**Comment by cjthedizzy** [comment]
Ready on https://github.com/MadeInHaus/react-redux-webpack-starter/pull/9

Needs testing

**Comment by cjthedizzy** [comment]
@stevescavo and @rynocouse, I merged this PR but I want to road test it before we close this issue.

**Comment by stevescavo** [comment]
I agree. Let's leave it open until it's running in production.

**Comment by unruffledBeaver** [comment]
This is working as intended now, closing
